Introduce CareerPath service doc
careerbuilder/DataScienceAPIDocumentation pull request #160
Opened 2020-08-18 01:55 UTC by psequeirag

2020-08-18 13:08 UTC, DavidGWu approved these changes

2020-08-21 16:53 UTC, akhilssct requested changes

2020-08-21 16:53 UTC, akhilssct commented on CareerPath.md
> +
The number of top n child nodes to select is a request parameter or hardcoded in code?

2020-08-21 20:30 UTC, akhilssct approved these changes

2020-08-24 17:03 UTC, psequeirag commented on CareerPath.md
> +
They may be, the underlying graph queries are not finalized. But if needed, such parameters will be added to the docs in a separate PR.

2020-08-24 17:03 UTC, merged

2020-08-24 17:04 UTC, psequeirag commented
Thanks for reviewing!